## Write a Numpy program to compute the multiplication of two given matrixes

In [2]:
import numpy as np 

def Multiplication (Matrix1 , Matrix2) : 
    return Matrix1 * Matrix2

Matrix1 = np.array([[1,2,3],
                    [4,5,6],
                    [7,8,9]])

Matrix2 = np.array([[9,8,7],
                    [6,5,4],
                    [3,2,1]])

print (f"The result of Multiplication : \n {Multiplication(Matrix1,Matrix2)}")

The result of Multiplication : 
 [[ 9 16 21]
 [24 25 24]
 [21 16  9]]


## Write a NumPy program to compute the determinant of a given square array

In [4]:
def Dete_Mat (Matrix):
    return np.linalg.det(Matrix)

Matrix2 = np.array([[9,8,7],
                    [6,5,4],
                    [3,2,1]])

print (f"the Deteminate of matrix  is  : {Dete_Mat(Matrix2)}")

the Deteminate of matrix  is  : -1.3322676295501906e-15


## Write a NumPy program to compute the cross product of two given vectors

In [6]:

def Cross_Prod (Vector1 , Vector2):
    return np.cross(Vector1,Vector2)

Vector1 = np.array([1,2,3])
Vector2 = np.array([5,6,7])
print (f"The result of cross product : {Cross_Prod(Vector1,Vector2)}")

The result of cross product : [-4  8 -4]


## Write a NumPy program to compute the condition number of a given matrix

In [7]:
def Cond_Num (Matrix): 
    Mat_Inv = np.linalg.inv(Matrix)
    Det_Mat = np.linalg.det(Matrix)
    Det_Mat_Inv = np.linalg.det(Mat_Inv)
    return Det_Mat*Det_Mat_Inv


Matrix2 = np.array([[9,8,7],
                    [6,5,4],
                    [3,2,1]])

print (f"the condition number of the matrix is : {Cond_Num(Matrix2)}")

the condition number of the matrix is : -1.5000000000000044


## Write a NumPy program to compute the inverse of a given matrix

In [14]:

Matrix = np.array([[9,8,7],
                    [6,5,4],
                    [3,2,1]])
Matrix_inv = np.linalg.inv(Matrix)

print (f"the inverse of the matrix is  : \n {Matrix_inv}")



the inverse of the matrix is  : 
 [[ 2.25179981e+15 -4.50359963e+15  2.25179981e+15]
 [-4.50359963e+15  9.00719925e+15 -4.50359963e+15]
 [ 2.25179981e+15 -4.50359963e+15  2.25179981e+15]]
the check of this matrix is inverse is  : 
 [[-1.    1.   -0.75]
 [ 2.   -4.    1.  ]
 [ 0.   -1.    1.75]]
