# NumPy Exercises 



#### Import NumPy as np

In [1]:
import numpy as np

#### Create an array of 10 zeros 

In [10]:
Zeros_Array = np.zeros(10)
print (Zeros_Array)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


#### Create an array of 10 ones

In [6]:
Ones_Array = np.ones(10)
print (Ones_Array) 

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


#### Create an array of 10 fives

In [7]:
Five_Array =5 * np.ones(10)
print (Five_Array) 

[5. 5. 5. 5. 5. 5. 5. 5. 5. 5.]


#### Create an array of the integers from 10 to 50

In [13]:
Array_Int = np.zeros(40)
Array_Int = [Counter+10 for Counter in range (0,len(Array_Int)+1) ]
print (Array_Int)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50]


#### Create an array of all the even integers from 10 to 50

In [49]:
Array_Even = np.zeros(40)
Array_Even = [ Counter+10   for Counter in range (0,len(Array_Even)+1) if Counter%2 ==0]
print (Array_Even)

[10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42, 44, 46, 48, 50]


#### Create a 3x3 matrix with values ranging from 0 to 8

In [61]:
Matrix_0_to_8 = np.zeros([3,3])
Counter =0 
for Row in range (0,Matrix_0_to_8.shape[0]):
    Counter = Row*3
    for Coloum in range (0,Matrix_0_to_8.shape[1]):
        Matrix_0_to_8[Row][Coloum] = Counter+Coloum

print (Matrix_0_to_8)

[[0. 1. 2.]
 [3. 4. 5.]
 [6. 7. 8.]]


#### Create a 3x3 identity matrix

In [63]:
I = np.identity(3)
print(I)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


#### Use NumPy to generate a random number between 0 and 1

In [64]:
Random = np.random.rand(3,2)
print (Random)

[[0.63841753 0.55597183]
 [0.16895667 0.39847667]
 [0.18982708 0.82653974]]


#### Use NumPy to generate an array of 25 random numbers sampled from a standard normal distribution

In [69]:
Random_Number = np.random.randn(5,5)
print (Random_Number)

[[ 0.63810876 -1.20153938 -1.1707207   0.17485655 -1.5212686 ]
 [ 0.8015649  -0.11420598 -0.68374818 -0.39187529  0.65234785]
 [-2.33436846  1.19833226  0.8259562   0.68677155  0.6368675 ]
 [-0.85117066 -0.39227874 -0.21563816 -1.93481868  1.46751824]
 [ 0.586173    0.96397103 -0.79441367  1.37428292 -0.73223215]]


#### Create the following matrix:

In [78]:
Matrix_1 = np.zeros([10,10])
for Row in range (0,Matrix_1.shape[0]):
    for Coloum in range (0,Matrix_1.shape[1]):
        Matrix_1[Row][Coloum] = 0.1*Row +0.01*Coloum + 0.01


print (Matrix_1)

[[0.01 0.02 0.03 0.04 0.05 0.06 0.07 0.08 0.09 0.1 ]
 [0.11 0.12 0.13 0.14 0.15 0.16 0.17 0.18 0.19 0.2 ]
 [0.21 0.22 0.23 0.24 0.25 0.26 0.27 0.28 0.29 0.3 ]
 [0.31 0.32 0.33 0.34 0.35 0.36 0.37 0.38 0.39 0.4 ]
 [0.41 0.42 0.43 0.44 0.45 0.46 0.47 0.48 0.49 0.5 ]
 [0.51 0.52 0.53 0.54 0.55 0.56 0.57 0.58 0.59 0.6 ]
 [0.61 0.62 0.63 0.64 0.65 0.66 0.67 0.68 0.69 0.7 ]
 [0.71 0.72 0.73 0.74 0.75 0.76 0.77 0.78 0.79 0.8 ]
 [0.81 0.82 0.83 0.84 0.85 0.86 0.87 0.88 0.89 0.9 ]
 [0.91 0.92 0.93 0.94 0.95 0.96 0.97 0.98 0.99 1.  ]]


#### Create an array of 20 linearly spaced points between 0 and 1:

In [79]:
Arr = np.linspace (0,1,20)
print(Arr)

[0.         0.05263158 0.10526316 0.15789474 0.21052632 0.26315789
 0.31578947 0.36842105 0.42105263 0.47368421 0.52631579 0.57894737
 0.63157895 0.68421053 0.73684211 0.78947368 0.84210526 0.89473684
 0.94736842 1.        ]


## Numpy Indexing and Selection

Now you will be given a few matrices, and be asked to replicate the resulting matrix outputs:

In [94]:
mat = np.arange(1,26).reshape(5,5)
mat

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [39]:
# WRITE CODE HERE THAT REPRODUCES THE OUTPUT OF THE CELL BELOW
# BE CAREFUL NOT TO RUN THE CELL BELOW, OTHERWISE YOU WON'T
# BE ABLE TO SEE THE OUTPUT ANY MORE

In [82]:
print (mat[2:,1:])

[[12 13 14 15]
 [17 18 19 20]
 [22 23 24 25]]


In [29]:
# WRITE CODE HERE THAT REPRODUCES THE OUTPUT OF THE CELL BELOW
# BE CAREFUL NOT TO RUN THE CELL BELOW, OTHERWISE YOU WON'T
# BE ABLE TO SEE THE OUTPUT ANY MORE

In [83]:
print (mat[3,4])

20


In [30]:
# WRITE CODE HERE THAT REPRODUCES THE OUTPUT OF THE CELL BELOW
# BE CAREFUL NOT TO RUN THE CELL BELOW, OTHERWISE YOU WON'T
# BE ABLE TO SEE THE OUTPUT ANY MORE

In [86]:
print(mat[:3,1].reshape(3,1))

[[ 2]
 [ 7]
 [12]]


In [31]:
# WRITE CODE HERE THAT REPRODUCES THE OUTPUT OF THE CELL BELOW
# BE CAREFUL NOT TO RUN THE CELL BELOW, OTHERWISE YOU WON'T
# BE ABLE TO SEE THE OUTPUT ANY MORE

In [87]:
print (mat[4,:])

[21 22 23 24 25]


In [32]:
# WRITE CODE HERE THAT REPRODUCES THE OUTPUT OF THE CELL BELOW
# BE CAREFUL NOT TO RUN THE CELL BELOW, OTHERWISE YOU WON'T
# BE ABLE TO SEE THE OUTPUT ANY MORE

In [88]:
print (mat[3:,:])

[[16 17 18 19 20]
 [21 22 23 24 25]]


### Now do the following

#### Get the sum of all the values in mat

In [89]:
print (np.sum(mat))

325


#### Get the standard deviation of the values in mat

In [90]:
print (mat.std())

7.211102550927978


#### Get the sum of all the columns in mat

In [103]:

sum_Col = np.zeros(mat.shape[1])
for Coloum in range (0,mat.shape[1]):
    sum_Col[Coloum]=np.sum(mat[:,Coloum])

print (sum_Col)



5
[55. 60. 65. 70. 75.]


# Great Job!